### PR TITLE
Fix PED bugs

### LINKED ISSUE #131: [PE-D] Inconsistent error messages for  the same type of incorrect syntax for [view] command
- Inconsistent syntax for view negative indices and view out of bounds positive indices
- Inconsistent syntax for view [name of person]
- Extends to other commands involving indices as well, like rm

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: lixiyuan416/ped#1

### LINKED ISSUE #134: [PE-D] Valid e-mail address is rejected
When editing or adding a new contact's email address, NUS email addresses such as `e1234567@u.nus.edu` are not accepted by the app. However, it meets the formatting rules stated in the error message. Perhaps the app could be designed to consider different types of valid email id formats.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: giterator/ped#2

### LINKED ISSUE #140: [PE-D] Overly restrictive input validation for email addresses
I am able to store/update most email addresses without any issue, however, there are email address formats that your software does not accept as valid email addresses. One such example is the NUS student email address in the format of `eXXXXXXX@u.nus.edu`. I personally believe this is a relatively significant flaw that could potentially affect many of your users.

Steps to reproduce:
1. run the command `edit me -e eXXXXXXXX@u.nus.edu`

Expected:
Email address is updated accordingly.

Actual:
Email address format is not accepted.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: brendanlsz/ped#1

### LINKED ISSUE #142: [PE-D] Unable to accept certain legitimate GitHub username.
According to GitHub, even though they do discourage having uppercase in their username, it is still acceptable. i.e. RemusTeo

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: markuslyq/ped#6

### LINKED ISSUE #145: [PE-D] Incomplete error message for invalid linkedin handle
When adding/editing a linkedin handle, the app appears to reject handles containing space characters. This condition is not specified in the error message shown to the user. 

This condition is currently included in the error message for entering an invalid name. You could consider adopting this for the linkedin handle error message to improve clarity. Both error messages are shown below:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: giterator/ped#6

### PR DESCRIPTION
**Pull request by mayankp291**
Summary of changes made : 

* Update email regex to include NUS emails
fixes #140 , fixes #134 
* Update Github regex to include uppercase
fixes #142 
* Fix inconsistent error messages for positive and negative index
fixes #131 
* Update Linkedin error message
fixes #145

### CODE REVIEW

File: src/main/java/seedu/parser/RegexParser.java [hunk 1]
```diff
@@ -96,7 +99,7 @@ protected void checkGithubUsernameRegex(String detailToParse) throws InvalidGith
         //GitHub username cannot have multiple consecutive hyphens.
         //GitHub username cannot begin or end with a hyphen.
         //Maximum is 39 characters.
-        String githubUsernameRegex = "^[a-z\\d](?:[a-z\\d]|-(?=[a-z\\d])){0,39}$";
+        String githubUsernameRegex = "^[a-zA-Z\\d](?:[a-zA-Z\\d]|-(?=[a-zA-Z\\d])){0,39}$";
```
Comment (ng-andre) [inline src/main/java/seedu/parser/RegexParser.java:102]: Fix for GitHub case sensitive name

File: src/main/java/seedu/parser/IndexParser.java [hunk 2]
```diff
@@ -13,7 +13,7 @@
     private static final int PERSONAL_CONTACT_ID = -1;
     private static final String REMOVE_ALL_INDEX = "all";
     private static final int REMOVE_ALL_ID = -2;
-    private static final String numbers = "[0-9]+";
+    private static final String numbers = "^-?\\d+$";
```
Comment (ng-andre) [inline src/main/java/seedu/parser/IndexParser.java:16]: Fix to allow negative numbers

File: src/main/java/seedu/parser/RegexParser.java [hunk 3]
```diff
@@ -57,9 +57,12 @@ public void checkRegex(String flag, String detailToParse)
 
     protected void checkEmailRegex(String detailToParse) throws InvalidEmailException {
         //allow lowercase email ids
-        String emailRegex = "^([\\w-\\.]+){1,64}@([\\w&&[^_]]+){2,255}.[a-z]{2,}$";
+        String emailRegex1 = "^([\\w-\\.]+){1,64}@([\\w&&[^_]]+){2,255}.[a-z]{2,}$";
+        String emailRegex = "^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|"
+                + "(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|"
+                + "(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
```
Comment (ng-andre) [inline src/main/java/seedu/parser/RegexParser.java:63]: Fix for .edu emails

**Review by ng-andre — APPROVED** [review]
LGTM! Comments are added for clarification when reviewing.
