### PR TITLE
JavaDoc, Updates to PPP and Bug fixing

### LINKED ISSUE #188: App crashes when name in contactx.txt, import.txt and me.txt is null

### LINKED ISSUE #189: "NULL" is accepted because of casing

### PR DESCRIPTION
**Pull request by lezongmun**
Fixes #188 
Fixes #189 

Summary:
- Added JavaDoc for functions
- Updated PPP
- Fixed the bug where app will crash when name is changed to null in contacts.txt and import.txt. 
- Fixed the bug where null strings are allowed due to casing

### CODE REVIEW

File: src/main/java/seedu/storage/ContactsDecoder.java [hunk 1]
```diff
@@ -173,8 +191,11 @@ private void handleInvalidDetails(Exception e, int lineIndex, String contactFile
             InvalidLinkedinUsernameException, InvalidEmailException {
         String[] destructuredInputs = contactText.split(SEPARATOR);
         String[] compiledDetails = new String[NUMBER_OF_FIELDS];
+        if (destructuredInputs[0].equalsIgnoreCase("null")) {
+            throw new InvalidNameException();
+        }
```
Comment (ng-andre) [inline src/main/java/seedu/storage/ContactsDecoder.java:196]: Good catch on the null bug!

**Comment by ng-andre** [comment]
LGTM overall, no issues with the documentation. Will leave the approval to @marcusbory as a second check for the bug fix, but otherwise I don't see any issues with it.

**Review by marcusbory — APPROVED** [review]
LGTM! Thanks for the thorough checks.
