### PR TITLE
IndexParser Bug Fixes

### LINKED ISSUE #160: Fix "me" index not working for some commands
Fix "me" index not working for view command. 
Shows invalid index instead of printing the personal contact.

### PR DESCRIPTION
**Pull request by ng-andre**
Fixes #160 
update code for order of getIndex to be consistent with the other parsers

### CODE REVIEW

File: src/main/java/seedu/command/ViewContactCommand.java [hunk 1]
```diff
@@ -19,9 +20,13 @@ public int getIndex() {
...
-            Contact viewingContact = contactList.getContactAtIndex(contactIndex);
-            assert contactIndex >= 0 && contactIndex < contactList.getListSize();
-            TextUi.viewContactMessage(viewingContact, contactIndex);
+            if (contactIndex == PERSONAL_CONTACT_ID) {
+                TextUi.viewPersonalContactMessage(this.personalContact);
+            } else {
+                Contact viewingContact = contactList.getContactAtIndex(contactIndex);
+                assert contactIndex >= 0 && contactIndex < contactList.getListSize();
+                TextUi.viewContactMessage(viewingContact, contactIndex);
+            }
```
Comment (mayankp291) [inline src/main/java/seedu/command/ViewContactCommand.java:29]: Nice and clean implementation, will fix the index "me" issue.

**Review by mayankp291 — APPROVED** [review]
Good job with the quick bug fixes. LGTM!
