### PR TITLE
Refactor exception handling and fixing some bugs

### LINKED ISSUE #163: Inconsistent error messages for edit, delete and view commands
Handle `edit`, `rm` and `view commands` when `all` and `me` are given in inputs. 
Change the error message from index out of bound to invalid/missing indexes.

### LINKED ISSUE #164: Missing parameters error message given for invalid indexes in edit command
`edit asd -n examplename`  and `edit -n examplename` gives missing parameters error message.

### PR DESCRIPTION
**Pull request by lezongmun**
Fixes #163 
Fixes #164 

Summary:
- Refactor exception handling in `edit` , `rm` and `view` commands to make them more readable
- Included an invalid index exception for `edit` for cases like `edit asd -n marcus` and `edit -n marcus` to give invalid/missing indexes message instead of just missing parameters message
- Updated UserGuide for `all` and `me` formats
- Updated error messages to be consistent with UserGuide

### CODE REVIEW

File: src/main/java/seedu/parser/IndexParser.java [hunk 1]
```diff
@@ -37,12 +36,12 @@ public static int getIndexFromInput(String userInput)
             return REMOVE_ALL_ID;
         }
         if (!significantIndex.matches(numbers)) {
-            throw new MissingIndexException();
+            throw new NumberFormatException();
```
Comment (ng-andre) [inline src/main/java/seedu/parser/IndexParser.java:39]: User input of index is not in valid regex therefore NumberFormatException. No issue here.

File: src/main/java/seedu/parser/MainParser.java [hunk 2]
```diff
@@ -29,6 +29,8 @@
 import seedu.exception.MissingDetailException;
 import seedu.exception.MissingIndexException;
 
+import java.lang.reflect.Array;
+
```
Comment (ng-andre) [inline src/main/java/seedu/parser/MainParser.java:33]: Probably an unused import that was added when using print statements for testing the array, can consider removing if not required.

File: src/main/java/seedu/ui/ExceptionTextUi.java [hunk 3]
```diff
@@ -128,6 +128,17 @@ public static void missingDetailMessage() {
         printDoubleLineMessage(message);
     }
 
+    public static void missingIndexEditMessage() {
+        String message = "There seems to be missing or invalid index in your request.\n"
+                + "Please enter command in the following way:\n"
+                + "      edit <INDEX> -n <NAME> -g <GITHUB> -e <EMAIL> -te <TELEGRAM> -l <LINKEDIN> -tw <TWITTER>\n"
```
Comment (ng-andre) [inline src/main/java/seedu/ui/ExceptionTextUi.java:134]: Can consider updating text with curly braces `{ }` for consistency with the UG.

File: src/main/java/seedu/command/EditContactCommand.java [hunk 4]
```diff
@@ -26,23 +27,25 @@ public void execute() {
...
                 updatePersonalContact();
+            } else if (contactIndex == ALL_CONTACTS_INDEX) {
+                ExceptionTextUi.missingIndexEditMessage();
             } else {
                 Contact editedContact = duplicateContact(contactList.getContactAtIndex(contactIndex));
                 editedContact.editContact(contactDetails);
                 handleDuplicates(editedContact);
             }
-        } catch (IndexOutOfBoundsException | InvalidFlagException e) {
+        } catch (IndexOutOfBoundsException e) {
```
Comment (ng-andre) [inline src/main/java/seedu/command/EditContactCommand.java:37]: Should InvalidFlagException still be caught here for safe measure? Considering most methods handle flags which throw InvalidFlagException, but if they are handled accordingly then there is no issue.

**Review by ng-andre — CHANGES_REQUESTED** [review]
Some nitpicks that can be looked into. If the issues higlighted do not affect the app functionality, do leave a comment accordingly and resolve them. Otherwise, will be ready to merge once the issues are resolved

**Review by ng-andre — APPROVED** [review]
Good job on the fixes, LGTM!
